language: python
cache: pip
dist: xenial

matrix:
  include:
    - python: 3.5
      addons:
        apt:
          sources:
            - ppa:mc3man/xerus-media
          packages:
            - ubuntu-restricted-extras
            - ffmpeg
            - libavcodec-extra
      before_script:
        ffmpeg --help
    - python: 3.6
      addons:
        apt:
          sources:
            - ppa:mc3man/xerus-media
          packages:
            - ubuntu-restricted-extras
            - ffmpeg
            - libavcodec-extra
      before_script:
        ffmpeg --help
    - python: 3.7
      addons:
        apt:
          sources:
            - ppa:mc3man/xerus-media
          packages:
            - ubuntu-restricted-extras
            - ffmpeg
            - libavcodec-extra
      before_script:
        ffmpeg --help
    - python: 3.6
      env: TOXENV=doc
    - python: 3.6
      env: TOXENV=check
  allow_failures:
    - env: TOXENV=check

install: pip install -U tox-travis

script: tox

after_success:
  - pip install codecov
  - codecov

notifications:
    irc: "chat.freenode.net#sigal"
