language: python
cache: pip
sudo: false

matrix:
  include:
    - python: 3.5
      addons:
        apt:
          sources:
            - trusty-media
          packages:
            - ubuntu-restricted-extras
            - ffmpeg
            - libavcodec-extra-54
    - python: 3.6
      addons:
        apt:
          sources:
            - trusty-media
          packages:
            - ubuntu-restricted-extras
            - ffmpeg
            - libavcodec-extra-54
    - python: 3.7
      dist: xenial
      sudo: true
      addons:
        apt:
          sources:
            - xerus-media
          packages:
            - ubuntu-restricted-extras
            - ffmpeg
    - python: 3.6
      env: TOXENV=check
  allow_failures:
    - env: TOXENV=check

install: pip install -U tox-travis

before_script:
  ffmpeg --help

script: tox

after_success:
  - pip install codecov
  - codecov

notifications:
    irc: "chat.freenode.net#sigal"
