language: python
cache: pip
sudo: false

python:
  - 3.6
  - 3.5

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
      env: TOXENV=check
  allow_failures:
    - env: TOXENV=check

addons:
  apt:
    sources:
      - trusty-media
    packages:
      - ubuntu-restricted-extras
      - ffmpeg
      - libavcodec-extra-54
      # Dependencies to build PIL
      - libfreetype6-dev
      - libjpeg8-dev
      - zlib1g-dev

install: pip install -U tox-travis

before_script:
  ffmpeg --help

script: tox

after_success:
  - pip install codecov
  - codecov

notifications:
    irc: "chat.freenode.net#sigal"
